sudo: required

language: go

go:
  - "1.13.7"

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  global:
    - CGO_ENABLED=1
    - GOBUILD="linux-amd64 windows-amd64 darwin-amd64"

script:
  - make -j ci
  - GOBUILD=${GOBUILD} make -j dist
  - ls -la build

  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=pr-$TRAVIS_PULL_REQUEST COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$TRAVIS_TAG" =~ ^v.*$ ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=$TRAVIS_TAG COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$BRANCH" == "master" ]]; then make -j docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS TAG=latest COMMIT=$TRAVIS_COMMIT; fi

deploy:
  provider: releases
  api_key:
    secure: iUEYgokutOO6dve8VEB6ZGzq2zaSczgg16HN01/Wb3R2j+YGwdm7Gwy9xB/QdEz9UPdBhZSpKzT6MzI3HCt5YliBdrbEsV3QTuLR5yVDegDwBpfHwxA+R8VjXKJPi65HZhnmCmsxhDwzPn1B01nzQVRvSz8hR/5J0Y+L6h37V10niuK0b5bsopucfyTvrhIZRoWVjvDOMJSiV4g9smEbPE3egdlLP+GEezIE2daSUdGdnfpVJk2VqfrHCU6n0gz1Dpv0+fSkGg/ypbNBmTOu4jnfklXuUhqdyLAr+gJW3bNnZDNVBK/Fa8Mp5kOKrPwGdbPfrjUo0KHipT3caDIGGAzgQZF21CiWzXOmzyW1cUXAO1OhFG8ZJNnyWFQ7dbxjTN5meyEOvTaxDi4rECsjblFj5m6JaexQwDy9lC1wm5vDxTC9dVG/ZcEXgtGOfJu/qOw44Bj/MIomc1mxVCjVB82MZBkUopGXRDm+kDSWkmXlD/NIUV00t6i7q33AkR0rCMqg7f/a5yHp/AlCR6mH/8PQe9GLxBrCUq2ufzLZmA9valRr/5/H8KQvDPhDI10+Df8fusBfH/iLKUOjC9TCN9at1KUQOvS467sM/nJSI0XsotWFGalkyytogfMxaXzuwSob/YgGf1aGTXmjjubiM96YHF8cUVLC623gGAHBoeQ=
  file:
    - build/hashi-helper-linux-amd64
    - build/hashi-helper-windows-amd64
    - build/hashi-helper-darwin-amd64
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: seatgeek/hashi-helper
